CREATE EXTERNAL TABLE [dbo].[aeris_billing_history] (
    [SUBSCRIBER_ID] VARCHAR (50) NULL,
    [DEVICE_ID] BIGINT NULL,
    [IMSI] BIGINT NULL,
    [ICCID] VARCHAR (50) NOT NULL,
    [MSISDN] BIGINT NULL,
    [BILL_PERIOD] INT NOT NULL,
    [BILL_PERIOD_YR] INT NOT NULL,
    [BILL_PERIOD_MO] INT NOT NULL,
    [BILL_STATUS] VARCHAR (50) NULL,
    [BILL_STATUS_START] DATE NULL,
    [BILL_STATUS_END] DATE NULL,
    [HOME_ZONE] CHAR (1) NULL,
    [ZONE_NAME] VARCHAR (50) NULL,
    [RATE_PLAN_START] DATE NULL,
    [RATE_PLAN_END] DATE NULL,
    [ACTIVE_DAYS_IN_PLAN] INT NULL,
    [PRORATE_FACTOR] FLOAT (53) NULL,
    [BILL_PKT_KB] INT NULL,
    [BILL_PKT_PRICE] FLOAT (53) NULL,
    [BILL_TOTAL_TRAFFIC_CHARGES] FLOAT (53) NULL
)
    WITH (
    DATA_SOURCE = [Aeris_Billing]
    );

